### ISSUE TITLE
Use database export to tests changes. 

### ISSUE THREAD

**Issue by rdok** [PadawanTony/BusTracker#11]
See https://github.com/PadawanTony/BusTracker/tree/AdminPanel/app/storage & https://github.com/PadawanTony/BusTracker/pull/10

**Comment by PadawanTony** [comment]
So you're going to use the export to test if the changes you made are ok?

Should I pull the request #10 or wait for this one?

**Comment by rdok** [comment]
Yes.  

Umm, I'll get to this on about 2 hours, so if you don't wait feel free to pull it. I just need to test home page. That jquery scares me lol.

**Comment by PadawanTony** [comment]
lol.

I'll pull it and try to solve any problems that may exist.

If I cannot do it, you can resolve them later. I will create issues.
