### ISSUE TITLE
[Hotfix]: getKifisaCoordinates

### ISSUE THREAD

**Issue by rdok** [PadawanTony/BusTracker#4]
[See](https://github.com/PadawanTony/BusTracker/blob/develop/app/Services/CoordinatesService.php#L81)

assigned: @rdok

**Comment by PadawanTony** [comment]
I think if we delete everything after :

```
$row = $stmt->fetch();
```

and we replace with:

```
$response["success"] = 200;
        if (empty($row))
        {
            $response["message"] = "No coordinates found.";
            return $response;
        }
        return $row;
```

it should get fixed?

**Comment by rdok** [comment]
@PadawanTony Yes, something along these lines. Just one function should suffice: [see](https://github.com/rdok/BusTracker/blob/feature/coordinates/app/Services/CoordinatesService.php#L53)

**Comment by rdok** [comment]
Damn, I was hoping those issues would be close from the commit. Seems they only work if you are the owner :/
