### ISSUE TITLE
Duplicate "use HubIT/App;"

### ISSUE THREAD

**Issue by PadawanTony** [PadawanTony/BusTracker#9]
Why do we need to use 

```
use HubIT\App;
```

in the admin_createRoute.php view, despite it being already in the admin.php layout that we are applying?

**Comment by rdok** [comment]
@PadawanTony You are right. 
- We should not have to use either the `use` or the classes inside the views at all. Thus we follow [conventions](https://github.com/PadawanTony/BusTracker/pull/10/commits/358a5bc3fc6d7ea88903c4a08c5ee1e32b693698#diff-8de8de075b65414d7b1268040594ee34R19).  
- You can pass the url function, or any other class function for that matter using the http://platesphp.com/engine/extensions/ .  
- Which for us [translates to](https://github.com/PadawanTony/BusTracker/pull/10/commits/358a5bc3fc6d7ea88903c4a08c5ee1e32b693698#diff-d0bf9edfd15d0d994aea4c8e69ac3512R12). And we can register these function at the base controllers. [Simple users](https://github.com/rdok/BusTracker/blob/AdminPanel/app/Controllers/Controller.php), and [admin users](https://github.com/rdok/BusTracker/blob/AdminPanel/app/Controllers/Admin/Controller.php).

**Comment by PadawanTony** [comment]
Omg. I see how this is a lot better than what I did.

I also see how it is a lot more complicated to understand!

Anyway, thx mate.
